version : !!str 3
services:
  nginx:
    image: nginx:1.20.2-alpine
    container_name: nginx
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
    ports:
      - "5352:80"
    restart: unless-stopped
    networks:
      - mynet
  respina:
    build: .
    image: respina:latest
    container_name: respina
    restart: unless-stopped
    networks:
      - mynet       
networks:
  mynet:  
    name: mynet
